"""empty message

Revision ID: 41e5e60c8d52
Revises: b3a5097900ea
Create Date: 2019-11-17 11:38:43.974983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e5e60c8d52'
down_revision = 'b3a5097900ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
